name: generate panvimdocs

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate vimdoc
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: portal
          version: "NVIM v0.9.0"
          demojify: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): auto generate docs"
          branch: ${{ github.head_ref }}
